### ISSUE TITLE
goofile issue

### ISSUE THREAD

**Issue by BlAd373** [leebaird/discover#105]
Hello to everyone and thank you in advance
Using kali 2017 how can i fix this issue?

goofile                   (5/32)
./discover.sh: line 297: goofile: command not found
./discover.sh: line 298: goofile: command not found
./discover.sh: line 299: goofile: command not found
./discover.sh: line 300: goofile: command not found
./discover.sh: line 301: goofile: command not found
./discover.sh: line 302: goofile: command not found
./discover.sh: line 303: goofile: command not found
./discover.sh: line 304: goofile: command not found

**Comment by L1ghtn1ng** [comment]
Hi, you need to run the update.sh which will install the dependencies for discover also can you run lsb_release -a and show me the output of that as well. Then please report back.
________________________________

**Comment by BlAd373** [comment]
Updating Discover.
fatal: Not a git repository (or any of the parent directories): .git

No LSB modules are available.
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	kali-rolling
Codename:	kali-rolling

**Comment by L1ghtn1ng** [comment]
If you read the readme file it will give you the instructions of how to clone the repo and then run the update.sh
________________________________

**Comment by BlAd373** [comment]
Done as from file Readme  but it does not work just goofile

**Comment by L1ghtn1ng** [comment]
Then run  apt install goofile in a terminal and then try again.

________________________________

**Comment by BlAd373** [comment]
Perfect now works was the lack of goofile installation
Sorry the disturbance

**Comment by leebaird** [comment]
I recently removed goofile from the update script, because I received an email from the Kali dev on a 2 year old ticket requesting that goofile be added. I thought they had pushed this. If not, then we will need to add that back into the update script. I'm also in the process of modifying a new version of the apt, which is located in discover/mods/goofile. This will become the script we will be using.
