### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by anarchia1** [leebaird/discover#106]
Dear Lee,

I just used the ptf tool from Dave kennedy for upgrading all my tools and when I launched discover it get me following error

root@KL:~# discover
/pentest/intelligence-gathering/discover/discover.sh: line 3652: syntax error near unexpected token `<<<'
/pentest/intelligence-gathering/discover/discover.sh: line 3652: `<<<<<<< HEAD'

I had another pc with a previous version of discover without the ptf tool, I just update this discover and having the same error.

I have looking for the issue but I'm unable to find the problem sorry ...
Please let me understand the problem.

Thanks in advance.

Kind regards,

**Comment by anarchia1** [comment]
Dear Lee,

if I comment out the line 3652 till 3658 it's back working again.

Kind regards,

**Comment by anarchia1** [comment]
Lee,

and if I let it run now, ge goes into recon-ng with follwing

[!] Script file '/pentest/intelligence-gathering/discover/passive.rc' not found.

Kind Regards,

**Comment by L1ghtn1ng** [comment]
The error with the head comment is due to a odd merge need to do some digging to fix it and not to sure with the RC file part
________________________________

**Comment by anarchia1** [comment]
Ok thank you very much for you feedback.

It still work like expected getting all the info like designed only that it's opening recon-ng with the .RC file when you exit recon-ng the discover script continue opening all the sites and have gathering all the data.

Thanks,

Kind Regards,

**Comment by L1ghtn1ng** [comment]
I have fixed the first issue you was having so do a git pull to get the
latest fix.

**Comment by anarchia1** [comment]
Thank you.

I close this case problem solved.

Kind Regards,
