### ISSUE TITLE
Whois Whitelisting

### ISSUE THREAD

**Issue by sonofapharmacist** [leebaird/discover#112]
it looks like whois no likey bots anymore

from the end of a whois entry;

"WHOIS consumers who are now receiving masked data can visit:
get whitelisted, to get unmasked data via Port 43. Find instructions
on how to apply for whitelisting here:"

**Comment by L1ghtn1ng** [comment]
Thank you for the report, this will be looked into.
________________________________

**Comment by L1ghtn1ng** [comment]
@sonofapharmacist I have tried multiple times to reproduce this and am not able to. Can you give me steps to reproduce this please?

**Comment by L1ghtn1ng** [comment]
Turns out this is not a problem. It is due to the new rules that are getting applied for privacy
