### ISSUE TITLE
theHarvester -b all never completes. 

### ISSUE THREAD

**Issue by jedrickj** [leebaird/discover#115]
It just hangs forever. It did include the domain I was searching for I took it out above. I commented it out in the script and the script drove on. I could see all of the below in the process table.

$theharvester -d $domain -b all  | grep $domain | sed 's/:/ /g' | tr '[A-Z]' '[a-z]' | column -t | sort -u > zall 

Rick

**Comment by leebaird** [comment]
theharvester has changed the way it deals with the maximum number of results for bing, google, and pgp. Working on it now.

**Comment by leebaird** [comment]
This has been fixed. Thanks for bringing it to my attention.

**Comment by jedrickj** [comment]
Thanks Lee I appreciate it.
