### ISSUE TITLE
Domain Passive Search hangs on theHarvester

### ISSUE THREAD

**Issue by ocasagrande** [leebaird/discover#118]
After my first use I ran update.sh and everything was fine.
Doing the first passive domain search, when Discover gets theHarvester step 16/26 (PGP search module) get stuck and nothing else happens.
![image](https://user-images.githubusercontent.com/16839043/46144452-fc2ca780-c22a-11e8-9205-594265ea546f.png)

**Comment by leebaird** [comment]
This is a bug within theHarvester. I will submit a bug report to that repo. Also, I will request that the repo on Kali be upgraded from 2.7.2 to the latest version of 3.0

**Comment by leebaird** [comment]
Reported to the Kali devs.
https://bugs.kali.org/view.php?id=5018

**Comment by leebaird** [comment]
PGP is working, it just takes a lot longer than the other theHarvester modules.
