### ISSUE TITLE
Firefox tabs unable to open

### ISSUE THREAD

**Issue by sonofapharmacist** [leebaird/discover#120]
Heyo, firefox tabs getting all messed up lately.  Now that i've looped the thing through a batch of domains to roll through active and passive recon i am drowning in broken firefox.  Things to note: i'm doing this through x11 forward over ssh, so therein could lie an issue. But criminy these tabs will be giving me bad dreams.

Anything that i need to do with this or should i just comment out poppin tabs altogether for batching domains?  the fork that i'm rolling from, but not relevant because it exhibits same behavior just on smaller scale with your branch [https://github.com/sonofapharmacist/discover/blob/master/disco_list.sh](url)
![firefox](https://user-images.githubusercontent.com/15661537/46702877-db812c00-cbf2-11e8-8101-28362f014a33.png)

**Comment by L1ghtn1ng** [comment]
Hi sonofapharmacist, Thanks for the report and by the sounds of it that
is the issue as this should be run locally. 

I would do as you suggested to get around the issue that you are
having. Not to sure what else we could do for this one I am afraid.
