### ISSUE TITLE
Adding API keys?

### ISSUE THREAD

**Issue by Zormgard** [leebaird/discover#121]
Hey there.

Love this tool, but i cant figure out, where im surpose to add them.?

Zormgard

**Comment by TheRapture** [comment]
Hey Zormgard! 
So to add keys, you just type in `recon-ng`  (Without quotes) and then you will type in whichever of the below options you have a key for. =)  Hope that helps!
  ```
keys add bing_api <value>
  keys add builtwith_api <value>
  keys add fullcontact_api <value>
  keys add github_api <value>
  keys add google_api <value>
  keys add google_cse <value>
  keys add hashes_api <value>
  keys add shodan_api <value>
```

**Comment by leebaird** [comment]
Thanks TheRapture, this answer is correct.
