### ISSUE TITLE
"rm" errors thrown after Whatweb executes

### ISSUE THREAD

**Issue by joacole** [leebaird/discover#125]
Hi Lee-

Discover is a darned useful tool. Thank you for all of your hard work and effort to bring it to the community.

This is a "works as intended, but maybe a more elegant solution can be found" question. In line 1093 of discover.sh, the script attempts to find and delete all empty files starting from "/". The effect of this is that after Whatweb runs in an active domain recon, a bunch of "rm" permission errors are thrown because the command is trying to remove items in directories like /proc and /dev.

Would it be just as useful to have that "find" and "rm" line operate on $home/data/$domain only or is there other cleanup that needs to be done outside of that directory? I apologize if this has already been addressed elsewhere, but I couldn't find reference to it in the issues log.

Thanks so much!

**Comment by L1ghtn1ng** [comment]
Hi joacole, thanks for the kind words, thanks for the suggestion I will look at getting that fixed or if you would like you can create a pull request if you would like to contribute?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by joacole** [comment]
Sure thing! I’ll do the pull request now. :-)

Merry Christmas!

**Comment by L1ghtn1ng** [comment]
Merry Christmas and thank you for the contribution

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by L1ghtn1ng** [comment]
Fixed with https://github.com/leebaird/discover/commit/ce3234a44fc691ed24d9012b2530ac7dd1804e5e
