### ISSUE TITLE
discover outputs errors on passive domain scan

### ISSUE THREAD

**Issue by Ddest** [leebaird/discover#127]
when i installed the discover script in kali linux i found it 2 places : /opt/discover and  /lib/live/mount/persistence/sdb2/rw/opt/discover. And the bad thing is that they are linked, it means that when i change one file's name the other changes too. This has created a lot of bugs especially in domain passive scans .

**Comment by leebaird** [comment]
I have no idea how this could have occurred. I have been running passive scans for 2 weeks straight with no issues.
