### ISSUE TITLE
subdomain problem

### ISSUE THREAD

**Issue by TerickJojo** [leebaird/discover#128]
I have updated the discover today and ran a passive recon. Finally, the result html page do not show any subdomain up. Then I check the detail and find recon-ng did the subdomain's research. However, nothing in report.

Thanks so much

**Comment by leebaird** [comment]
Please retest your results now.

**Comment by TerickJojo** [comment]
yeah, subdomains have came back. But there is still a flaw
![image](https://user-images.githubusercontent.com/24235319/55996168-74a90200-5c6b-11e9-8353-8306999db3c1.png)

**Comment by leebaird** [comment]
Your problem is not with Discover, its with theHarvester. I just ran: rm -rf  /opt/theHarvester/
Then run update from the Discover menu. This should reinstall theHarvester and install the necessary requirements.

**Comment by TerickJojo** [comment]
thank you so much, bro.
