### ISSUE TITLE
crt.sh crash

### ISSUE THREAD

**Issue by leebaird** [leebaird/discover#133]
crt.sh                                    (33/39)
Traceback (most recent call last):
   File "parsers/parse-certificates.py", line 6, in <module>
      from texttable import Texttable
ImportError: No module named texttable

**Comment by L1ghtn1ng** [comment]
Check the requirements.txt file if not in there I can add it later

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by L1ghtn1ng** [comment]
@leebaird its in https://github.com/leebaird/discover/blob/master/notes/python/discover/requirements.txt so just a pip install is needed

**Comment by leebaird** [comment]
Thanks for the fix today Jay. Much appreciated!

**Comment by L1ghtn1ng** [comment]
You are welcome
________________________________
