### ISSUE TITLE
recon-ng incompatibility 

### ISSUE THREAD

**Issue by WitcherDev** [leebaird/discover#134]
Hi all,
on my kali linux i have recon-ng version 5.0.0. I have discovered that Discover doesn't work with that version of recon-ng (which is the newest).

Troubles start with ./update.sh not installing proper recon-ng modules, and end with
> recon-ng: error: unrecognized arguments: --no-check
error when trying to run ./discover.sh on test.pl site.

https://pastebin.com/QUH49B56

When removing --no-check attribute we can clearly see root of the problem. Even first command:
> woskspaces add test.pl
result in an error, since 'add' is not listed as avaliable option.

https://pastebin.com/kfzt6bav

**Comment by L1ghtn1ng** [comment]
Hi thanks for the report and information, this will be looked at asap
________________________________

**Comment by leebaird** [comment]
I took a first stab at fixing all of the problems on Friday. 
Please retest.

**Comment by PatrickFarley-Grant** [comment]
Hi, does anyone know how to clear the dashboard in recon, im new at this so I would like some help

**Comment by rogermanich** [comment]
@PatrickFarley-Grant if you want to clear the screen now you should use shell clear. In general shell <command>. I've seeen in this version they change a lot of commands.

**Comment by eliassal** [comment]
Hi, I have downloaded the kali linux 2020, fresh new setup yesterday. "db insert domains" works fine but not "db insert companies
I am getting the following error

> [recon-ng][sierac][ipinfodb] > db insert companies Sierac
> **[!] Columns and Values length mismatch**

Also, can you please let me know what command to use for deleting a domain? Thanks

**Comment by kpomeroy1979** [comment]
Hi,

I actually didn’t know the command to create a domain so thanks for
mentioning it. I use the SQLLite browser in Kali and open the database and
add a domain and company that way. Also, if you run discover scripts it
will create the company and domain for you.
