### ISSUE TITLE
Conflict with other files of same name

### ISSUE THREAD

**Issue by Intek13x** [leebaird/discover#138]
discover.sh doesn't run if there is a file of same name in any location/directory. Other scripts in different locations works properly except for this one (/opt/discover/discover.sh) 
> ┌─[x230@ThiccPad]─[~]
> └──╼ $sudo /opt/discover/discover.sh 
> 
> ================================================================== 
> 
> Found 4 instances of Discover on your system.
> Refer to the following paths:
> 	/home/x230/discover.sh
> 	/home/x230/Downloads/discover.sh
> 	/opt/discover/discover.sh
> 	/usr/share/sniper/modes/discover.sh
> 
> Remove or rename all but the install path and try again.
> If renaming, 'discover.sh' can't be in name. Try 'discover.bu' etc.
> 
> ================================================================== 

> 

Even after renaming it to discover.bu, it doesn't work properly.

**Comment by ninewires** [comment]
Did you run updatedb after the file rename?

**Comment by Intek13x** [comment]
> Did you run updatedb after the file rename?
Tried it, just one less instance of Discover found. Discover script is still not running.

**Comment by ninewires** [comment]
You should not be renaming Discover’s discover.sh.  The files located with the home directory would be unnecessary after install. That’s said, the discover.sh used by sniper will still cause an issue. I will get this in the todo list to update the discover install location check.

**Comment by L1ghtn1ng** [comment]
Jason, is possible to not care where it gets installed?
________________________________

**Comment by Intek13x** [comment]
> You should not be renaming Discover’s discover.sh. The files located with the home directory would be unnecessary after install. That’s said, the discover.sh used by sniper will still cause an issue. I will get this in the todo list to update the discover install location check.

Oh i know, but would not it break other scripts? 

I think it would be better to use default location of Discover(/opt/discover/discover.sh) instead of "tmpinstance" in script.

**Comment by ninewires** [comment]
That won’t work when you don’t run the script from the install directory.

**Comment by ninewires** [comment]
That is not a default location. It may be for Kali, but is not for PTF.

**Comment by Intek13x** [comment]
> That is not a default location. It may be for Kali, but is not for PTF.

Now i get it. Thanks for helping.
