### ISSUE TITLE
New tool instead nmap  [enhancement]

### ISSUE THREAD

**Issue by sophisticcitizen** [leebaird/discover#139]
Using [Spyse](https://spyse.com) API you probably double up the speed of data collection. Hope this will help you

**Comment by L1ghtn1ng** [comment]
As discover uses theHarvester once have a look at spyse then it will be easier for us to update discover to use it
________________________________

**Comment by L1ghtn1ng** [comment]
For anyone that sees this please look at https://github.com/laramies/theHarvester/issues/306

**Comment by leebaird** [comment]
Thanks for the heads up on the new tool. I know that theHarvester team is working on it now. Once that is complete, we will add it to Discover.
