### ISSUE TITLE
1. Domain > 1. Passive exits back to Main Menu

### ISSUE THREAD

**Issue by sonofapharmacist** [leebaird/discover#145]
On two different boxes the 1. Domain to 1. Passive selection brings you back to the main menu.

This happens after running the passive once before.

If I rm -rf *.sh from the discover/ and git reset --hard i can run the passive once, then same issue.

**Comment by sonofapharmacist** [comment]
still getting same even after rm -rf discover/ totally and git clone discover run update.sh again, same procedure gets me passive exiting back to main menu

**Comment by leebaird** [comment]
Should now be fixed.

**Comment by BrianSandro** [comment]
Does anyone else have this problem after a git pull? Im encountering the same issue now too :(

**Comment by L1ghtn1ng** [comment]
Are you using the most recent checkout of git?
________________________________

**Comment by BrianSandro** [comment]
Thank you for replying so quick! Yes i have. Running this on a Kali box, ill try my Ubuntu box to be certain.

**Comment by L1ghtn1ng** [comment]
Will have a look later unless lee beats me to it

________________________________

**Comment by BrianSandro** [comment]
Appreciating your effort!

**Comment by Marclay-Associates** [comment]
This isn't fixed for me on the latest pull.

**Comment by M-Associates** [comment]
Ah, I just noticed there is no passive.sh file, no idea how it got deleted. Have added it back in and menu works again

**Comment by BrianSandro** [comment]
Yesss! Thank you, this did the trick!

> Ah, I just noticed there is no passive.sh file, no idea how it got deleted. Have added it back in and menu works again
