### ISSUE TITLE
Running a Passive scan deletes passive.sh

### ISSUE THREAD

**Issue by M-Associates** [leebaird/discover#146]
Everytime I run a passive scan from the latest pull, it completes then when I go to run another the passive.sh file has been deleted somehow. The only way round this is to create a new passive.sh file and chmod after each run.

**Comment by 3levated-Kn0wledge** [comment]
Hey,

Hope this helps, did a bit of a workaround for this issue which I've copied below.

Step 1: copy  passive.sh file to root folder

Step 2: open domain.sh file and replace
`1) $discover/passive.sh && exit;;`

With

`1) cd; cp passive.sh /root/discover; cd /root/discover; chmod +x passive.sh; $discover/passive.sh && exit;;`

Hope that makes sense :)

**Comment by leebaird** [comment]
Found the mistake, changed line 788 in passive.sh 
mv passive* $home/data/$domain/tools/recon-ng/
to
mv passive.rc passive2.rc $home/data/$domain/tools/recon-ng/
