### ISSUE TITLE
speed improving [enhancement]

### ISSUE THREAD

**Issue by Luci-d** [leebaird/discover#147]
i would suggest using spyse API for some scans like IP, CIDR, domains/subdomains etc. it will give you much faster results

**Comment by leebaird** [comment]
2 of us are on the dev team for theHarvester. We are going put that in the que for a new module. Once that is complete, we will add that to Discover. Good find, thanks!

**Comment by Luci-d** [comment]
> 2 of us are on the dev team for theHarvester. We are going put that in the que for a new module. Once that is complete, we will add that to Discover. Good find, thanks!

oh cool, glad to help
