### ISSUE TITLE
i got error after opening theHarvester..plzz help

### ISSUE THREAD

**Issue by abhishekborse111** [leebaird/discover#149]
theHarvester.py: error: the following arguments are required: -d/--domain

**Comment by L1ghtn1ng** [comment]
Can you please send me the output of your cli to see the process that you are doing to run this, I have a feeling you have posted this on the wrong project. Correct me if I am wrong?
________________________________

**Comment by L1ghtn1ng** [comment]
Closing this out as this is the wrong repo for this and timeout
