### ISSUE TITLE
problem 

### ISSUE THREAD

**Issue by shanow7** [leebaird/discover#151]
the problem is:

![image](https://user-images.githubusercontent.com/37192410/73139384-dbb66c80-406d-11ea-82c0-3a6131ab9e82.png)

**Comment by L1ghtn1ng** [comment]
What is the domain that you are using?
________________________________

**Comment by shanow7** [comment]
sony.com

**Comment by L1ghtn1ng** [comment]
I do not get that error when I try it, the only time you will get that error is if you are being intercepted by a proxy or the sites certificate has expired, in this case it is not the site as I checked, so there is some other factor in it which is probably a proxy. You can modify  https://github.com/leebaird/discover/blob/1fc76b0f300ab290feed16d5961a07612cb80f48/mods/goofile.py#L31
and include the verify=False switch, I recommend against that as it has security implications

**Comment by shanow7** [comment]
thanks for information :) 
I think this project is brilliant and I hope that you will develop it with more modules :) maybe something about:
- social media e.g. sherlock https://github.com/sherlock-project/sherlock or https://github.com/Cignoraptor-ita/cignotrack
- phone number https://github.com/sundowndev/PhoneInfoga
can you extend recon-ng with HDE Recon-ng module?
