### ISSUE TITLE
Names and emails not importing from recon-ng

### ISSUE THREAD

**Issue by Slad3G** [leebaird/discover#153]
Hey Lee,

Thanks for your hard work on this great tool. I noticed today that after running the update.sh script that my recon-ng workspace created by diiscover had 71 contacts and 9 credentials but the discover report itself showed no names or emails. I know Tim has been making a lot of changes and improvements to recon-ng and wondered if maybe that has affected data import. The other data regarding domains and hosts appears to be accurately exported and imported.

Thanks again,

SG

**Comment by leebaird** [comment]
Tim has completely rewritten his tool. Unfortunately HE is the only person that seems to be able to use it. The documentation is terrible, if it even exists at all. I'm trying to keep up with it the best I can. The project has become almost useless.

**Comment by Slad3G** [comment]
Hey Lee,

Thanks for the response. I understand it can be hard to incorporate tools, Tim is really a great guy so I'm sure we can get an answer to anything you'd like. Is there something in particular you need? I don't mind digging into the recon-ng code to look around.

S

**Comment by leebaird** [comment]
Send me an private email so that we can work together on this issue.
