### ISSUE TITLE
Running on kali 2020.1 

### ISSUE THREAD

**Issue by cuato21** [leebaird/discover#157]
I need help, when I run de discover script on the new kali linux it gives me the next error. 

**_Scan complete.***

The supporting data folder is located at /root/data/www.fonadin.gob.mx/

Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /home/kali/.Xauthority which is owned by kali.)
Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /home/kali/.Xauthority which is owned by kali.)
Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /home/kali/.Xauthority which is owned by kali.)_**

**Comment by L1ghtn1ng** [comment]
Okay thanks for the report
________________________________

**Comment by leebaird** [comment]
Please do a git pull and test again.

**Comment by leebaird** [comment]
Discover was meant to be ran as root.
Please join our Slack channel to discuss more.
discover-pentest.slack.com
