### ISSUE TITLE
Recon-ng-Modules

### ISSUE THREAD

**Issue by shanow7** [leebaird/discover#165]
hi, I have a question regarding the program, why are harvester results such as mail not included in the report? next, where to put api keys used in recon-ng so that they are used during passive search? can you add such modules to recon-ng https://github.com/Dec0ne/Recon-ng-Modules

**Comment by leebaird** [comment]
1. Those results are aggregated with similar results from other tools.
2. recon-ng
keys list              # Show keys
keys add <name> <API key>
