### ISSUE TITLE
Passive Recon AMASS stuck

### ISSUE THREAD

**Issue by sematpran** [leebaird/discover#169]
Hi, i've this problem immediately after i run the passive recon. It gets stuck in the AMASS part and nothing happens. I runing this tool in Kali linux 2020.4 x64. Anyone knows how to solve this problem? Thks

![Screenshot_4](https://user-images.githubusercontent.com/59423760/108119310-5b9ae480-707e-11eb-9c55-6abf2197f213.png)

**Comment by kpomeroy1979** [comment]
I think you need to make sure Amass is installed and that the report
passive.sh script references it. Also, make sure you have the latest
version of Amass installed.

You could comment that part out of the Passive.sh they launched amass to
skip over it.

Hope this helps

**Comment by sematpran** [comment]
I comment that part and it works, skiping ammas. Thanks you very much

**Comment by L1ghtn1ng** [comment]
Did you run update.sh? As that sets everything up etc?
________________________________

**Comment by sematpran** [comment]
Yes i did, it didn't work, I had to comment that part

**Comment by L1ghtn1ng** [comment]
if you uncomment it and do a git pull then run update.sh that should now work correctly for you

**Comment by sematpran** [comment]
Yes, later i update the AMASS and work perfectly. Thanks you
