### ISSUE TITLE
Problem Recon-ng

### ISSUE THREAD

**Issue by sematpran** [leebaird/discover#170]
Hi, i've a problem with the passive recon. A while after the tool loads all 46 modules and starts working with the recon-ng, it stucks in this part. I tried to run update.sh and it didn't work. I'm using recon-ng v5.1.1. Any idea of how to solve this problem. Tnks

![Screenshot_5](https://user-images.githubusercontent.com/59423760/108205535-f558a500-7103-11eb-8b4d-ec2ebbde12e6.png)

**Comment by L1ghtn1ng** [comment]
do bash -x discover.sh and when it gets to that what errors are being shown?

**Comment by sematpran** [comment]
Hi, i run "bash -x discover.sh" and start doing this:

![image](https://user-images.githubusercontent.com/59423760/108441387-c6415100-7233-11eb-8280-ff77864c1615.png)

![image](https://user-images.githubusercontent.com/59423760/108441417-d48f6d00-7233-11eb-95dd-5cb5f6212155.png)

but when it gets to the error part, nothing diferent happend

![image](https://user-images.githubusercontent.com/59423760/108441130-3e5b4700-7233-11eb-89f0-bfd350ca63ec.png)

**Comment by leebaird** [comment]
Unfortunately, recon-ng relies on third party resources which often break, which cause Discover to break.
Figure out which recon-ng module is breaking, then report the bug to that project.
