### ISSUE TITLE
Passive mode. I got no results.

### ISSUE THREAD

**Issue by N1c0Ma** [leebaird/discover#174]
Hi,

I recently started to use Kali Linux and tried discover, but it doesn't work for me. I've got no results.
I clone discover from its repository into /opt/discover/ and run ./update.sh via sudo and then ./discover.sh via sudo.

The scanned reddit.com, the result should be in the folder of /root/data/www.reddit.com/, but I can't access it. I could via root-user, but the results html-pages are almost empty.

I've got some error-messages:
for recon-ng: 
[!] 'censysio_id' key not set. censys_netblock_company module will likely fail at runtime. See 'keys add'.
and so on.

In the summary: 
[recon-ng][www.reddit.com][pen] > modules load recon/domains-contacts/metacrawler
[!] Invalid module name.

This one: 
WWW.REDDIT.COM

[!] 'HTMLParser' object has no attribute 'unescape'.
[!] Something broken? See https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting.

And this one multiple times, too: 
[recon-ng][www.reddit.com][hibp_breach] > run
[!] Source contains no input.

It ended with: 
No protocol specified
Unable to init server: Could not connect: Connection refused
Error: cannot open display: :0.0

What did I miss? Please help me.

**Comment by leebaird** [comment]
I always run Discover as root.
recon-ng is not well maintained to say the least.
Make sure you are running passive recon unless you have permission to do an active search.
Choose another target. Make sure you provide the company name and domain like ACME and acme.org
