### ISSUE TITLE
[Bug] parse-burp needs porting to py3

### ISSUE THREAD

**Issue by jasc22** [leebaird/discover#177]
I've tried installing lxml 3.4.2 in the latest version of Kali but it does not work. I've tried various ways to install it and no luck either way. It worked really well on 2020.1 with no issues. Appreciate if you can provide any assistance regarding this. Thanks!

**Comment by L1ghtn1ng** [comment]
The issue is due to this script and the other parsers needing to be ported to py3

**Comment by jasc22** [comment]
Thanks for your quick response and code update. I tested it and get "[!] Error processing file." If you would like a Burp xml file please let me know and I can make that available.

**Comment by jasc22** [comment]
Thanks, @L1ghtn1ng and @leebaird! Please find attached a test XML file.
[bsp_test.xml.zip](https://github.com/leebaird/discover/files/7324228/bsp_test.xml.zip)

**Comment by L1ghtn1ng** [comment]
@jasc22 Thanks for that, I have rewrote the script from scratch and I have it working, just got 1 bug to fix then can push it after that

**Comment by mohdjawad157** [comment]
> I've tried installing lxml 3.4.2 in the latest version of Kali but it does not work. I've tried various ways to install it and no luck either way. It worked really well on 2020.1 with no issues. Appreciate if you can provide any assistance regarding this. 



Hello,

I have an issue with the Recon options. When I try to select the Domain or Person options by putting the number on the option section and hitting "Enter" it does nothing.

I've updated and installed as the instructions given but still does nothing. Please advice.

I'm running Kali Linux release 2021.3

a r u getting any issues regarding tus
