### ISSUE TITLE
Cant get either of the Recon options working

### ISSUE THREAD

**Issue by Didgerydont** [leebaird/discover#183]
Hello there, 
I am just after installing discover onto Kali Linux 2022.1 and can't get many of the choices to work. As of right now options 3, 4 and 5 seem to be the only ones working for me. When I select the other choices, it takes the input but just comes back to a blank cursor. No errors are being thrown. I downloaded the package using...

`git clone https://github.com/leebaird/discover`

Any ideas if there are any fixes for this or if there is something else that I should be doing?

**Comment by leebaird** [comment]
I just tested  on a clean install of 2022.1 and everything works as expected.

**Comment by Didgerydont** [comment]
Hello again Leebaird,
Ive sorted it. I deleted the original file I installed, re-installed it in the /opt/ location, ran the update and deleted the version being stored in my trash and it worked a treat. Turns out I should have just done a better job of reading the documentation. Many thanks for your speedy reply all the same. Much appreciated!

**Comment by leebaird** [comment]
You got it, hope you enjoy the tool. Don't forgot to check out everything  in the  notes/ folder.

**Comment by anshu421** [comment]
hi leebaird ,
im getting the same thing need help

**Comment by anshu421** [comment]
my email is callofmactavish@gmail.com
