### ISSUE TITLE
Recon/Domain/Passive issues

### ISSUE THREAD

**Issue by Ciberramir52** [leebaird/discover#185]
When i try the tool with a given domain it get stuck and then some of the tools that uses give error because some documents doesn't exists.
![discovererror](https://user-images.githubusercontent.com/63085235/170760472-ee52a9cb-2cb9-4491-913a-2455fdef6632.PNG)
![image](https://user-images.githubusercontent.com/63085235/170760518-5a45205d-14df-4556-90f8-41eb8e31fade.png)

**Comment by leebaird** [comment]
I have used the domain recon several times in the past week with no issues on a brand new instance of Kali 2022.2. Suggest verifying the SHA256 hash when you d/l a virtual machine image. Follow the steps in the README. If you need additional help, provide your email and I'll send you an invite to our Slack channel.
