### ISSUE TITLE
Domain/Person Recon not working

### ISSUE THREAD

**Issue by veilevasion1337** [leebaird/discover#188]
Hello, when ever I click 1 to activate the domain or 2 for the person recon it doesn't react or give any error, it just ask for an input all over

**Comment by veilevasion1337** [comment]
jarviz101@gmail.com

**Comment by leebaird** [comment]
Invite sent.

**Comment by MarcoXM** [comment]
@leebaird Hey Lee, good afternoon, I have a similar issue when I going to use discover. Could I join the slack chat too? 
My email is marco@waleup.com

**Comment by leebaird** [comment]
Added same day.
