### ISSUE TITLE
Scripts don't run - returns to menu screen

### ISSUE THREAD

**Issue by KaiZenSec** [leebaird/discover#193]
When attempting to run a list scan or CIDR scan after the port scan is completed, the script returns to the main menu screen. The nmap scripts and MSF aux modules do not run. 

Python 3.10.5
Kali Rolling 2022.3
Virtualbox 6.1.36 (Windows)

**Comment by leebaird** [comment]
Thanks, I will look into this.

**Comment by leebaird** [comment]
Works for me. You need to realize that the NSE and MSF aux modules only run when there are matching open ports. The initial scan may not have found any open port.
