### ISSUE TITLE
domain not working

### ISSUE THREAD

**Issue by jdelacruz0209** [leebaird/discover#194]
domain and person not working I've been updating all. what should I do? I run the Root but still not working...

**Comment by leebaird** [comment]
Please provide your email so that I can add you to the Slack channel.

**Comment by jdelacruz0209** [comment]
stephenluna99@gmail.com

**Comment by leebaird** [comment]
I can't replicate your issue. Sent you an invite to Slack.

**Comment by leebaird** [comment]
The user was running ./passive.sh, which is wrong.
Just run ./discover.sh and use the menu.




[8:17](https://discover-pentest.slack.com/archives/D04216JP3QT/p1663075072922119)
Then use the menu options.
