### ISSUE TITLE
Domain passive recon - script ends, returns to main menu and outputs no results

### ISSUE THREAD

**Issue by neil-ham** [leebaird/discover#196]
Hi Lee, 
I'm having similar problems to previous issues posted here. Installed discover as per your instructions. I'm running Kali 2022.4 on VM Virtualbox, installed using an ISO file. The ISO file is Kali 2022.1 I updated to Kali 2022.4 before installing discover.

I run cd /opt/discover/ then sudo ./discover.sh

I select option 1 for domain, option 1 again for passive. 

Then enter company name: coolmore and domain: coolmore.com.au (I've also tried with tesla and tesla.com)

The script runs to the end, ends suddenly and returns to the main menu screen. No tab output to firefox, not sure if any results are stored anywhere. I am a noob so highly likely I've made a blunder somewhere. Any help much appreciated :)

![Screenshot from 2022-11-23 11-59-48](https://user-images.githubusercontent.com/118902465/203549571-2d01dd00-d746-4476-be82-4917ebf2053a.png)
![Screenshot from 2022-11-23 12-00-43](https://user-images.githubusercontent.com/118902465/203549868-a49d1c40-3b6f-4b61-89ea-96b2589924e5.png)

**Comment by leebaird** [comment]
I can confirm the behavior. Looking into it now.

**Comment by leebaird** [comment]
Fixed. Thanks for the bug report.

**Comment by neil-ham** [comment]
Working for me Lee. Thanks mate!
