### ISSUE TITLE
result page error

### ISSUE THREAD

**Issue by Gazel1** [leebaird/discover#197]
The results page does not open

[
![ayuda](https://user-images.githubusercontent.com/126425402/227064148-2564355e-0339-4462-ab20-f6797b358abc.PNG)

**Comment by Gazel1** [comment]
I run discover as sudo too

**Comment by Gray-0men** [comment]
Make sure whatever HTTP service you're using is also running as sudo since the data was written to disk with sudo permissions. I usually just used the `python -m http.server 80` command to get the job done to look at the data

**Comment by leebaird** [comment]
The issue is Kali won't let you open a local webpage as root.

When your scan completes, do the following as root:
mv /root/data/acme.org /home/kali/
chown -R kali:kali /home/kali/acme.org
Open a new tab in Terminal.
open acme.org/index.htm &

I may add this functionality soon.
