### ISSUE TITLE
delay and -g

### ISSUE THREAD

**Issue by sec13b** [leebaird/discover#198]
Remote Desktop
     sudo nmap -iL $name/3389.txt -Pn -n --open -p3389 --script-timeout 20s --script=rdp-vuln-ms12-020,rdp-enum-encryption,rdp-ntlm-info --min-hostgroup 100 -g $sourceport --scan-delay $delay > tmp

  
i dont understand -g what is exactly,  can show a example ? , and what is the best delay you use for pentest

thank you

**Comment by leebaird** [comment]
-g source port:
     Internal scans: set to 88 for Kerberos
     External scans: set to 53 for DNS

Both of these options are automatically set when you choose internal or external scan.
