### ISSUE TITLE
Support For ParrotSec 5.1

### ISSUE THREAD

**Issue by Dazmed707** [leebaird/discover#200]
PASSIVE DETECTION

![support](https://github.com/leebaird/discover/assets/35184132/7da5bcb7-cf7f-4ec3-a06a-b5eae8972fda)

**Comment by L1ghtn1ng** [comment]
parrotsec 5.1 is coming up to being a year old and 5.2 is out, do you have an issue after upgrading to that new release or parrot? https://parrotsec.org/blog/2023-02-15-parrot-5.2-release-notes

**Comment by L1ghtn1ng** [comment]
Turns out 5.3 is the latest that came out on may 1st

**Comment by L1ghtn1ng** [comment]
Found a solution in the end, run update.sh and you should be good

**Comment by Dazmed707** [comment]
I'm going to try the update, I was wrong, the version I use and that I posted the error was Parrot 5.3
