### ISSUE TITLE
ERROR: Cannot uninstall dnspython 2.6.1, RECORD file not found. Hint: The package was installed by debian

### ISSUE THREAD

**Issue by telva91** [leebaird/discover#203]
when i update the script 

it comes to scapy install
cretes wheels and 
this error
ERROR: Cannot uninstall dnspython 2.6.1, RECORD file not found. Hint: The package was installed by debian

i did check my system there is no dnspython 2.6.1 on my system what am i doing wrong please help

**Comment by telva91** [comment]
any body having the same problem here is what i did

at the moment it supports kali 2024.1

install it using iso immage - vmware vm dosen,t help
install go - installation stuck in the middle  (apt install golang-go)
pip install PyPDF3 (otherwise metacrawler been disabled)
CensysCertificates' from 'censys.search (needed for recon companies domain)
don't update kali by apt upgrade (it need to be done via script update)
you will be needing several api keys for full performance (eg: google api, shodan api,github api and more)

**Comment by leebaird** [comment]
I just tested this with a brand new VM of 2024.2.
No issues.
