### ISSUE TITLE
Firefox issues while running passive scan

### ISSUE THREAD

**Issue by CrazianT3k** [leebaird/discover#204]
Discover scripts was working in previous weeks. Today I ran update.sh and it updated error free. Then while running a passive scan as root user, I got firefox errors. I closed firefox after getting the errors and the script would continue for a bit then error out again. Please see screenshot for errors.

![image](https://github.com/leebaird/discover/assets/6651634/d9cfa58d-ba50-4910-b104-cfd9e13dc3e0)
![Greenshot 2024-07-08 17 10 55](https://github.com/leebaird/discover/assets/6651634/98062f15-676e-4205-ab59-a4a2fedebc4a)

**Comment by L1ghtn1ng** [comment]
That looks like your system needs a reboot to fix that error, then see if it does it afterwards

**Comment by CrazianT3k** [comment]
> That looks like your system needs a reboot to fix that error, then see if it does it afterwards 

Thank you for the quick reply! I did a system reboot before posting the issue. After the reboot, I ran another passive scan and got the same error.

**Comment by leebaird** [comment]
This error is not tied to Discover.
