### ISSUE TITLE
Script Doesn't Complete

### ISSUE THREAD

**Issue by Artifice-Sec** [leebaird/discover#208]
I have a new instance of Kali Linux that is fully updated and I went to install the discover script too but when I run it for a domain (passive or active), it fails to complete. Seems to be an error that causes it to stop prematurely. For domain -> passive, it stops after Email -> Names. For Domain -> Active, it runs sometimes when I give a .com address but something like a .us domain will have it stop right after the sub-domains enumeration part. Other times for domain active it will say, "line 35: company: unbound variable" when I give a .com address.

The error message /opt/discover/active.sh line 35: company: unbound variable indicates that the variable company is being used before it has been assigned a value. This error occurs because the script is using the set -u option (from set -euo pipefail), which treats any unset variables as an error.

Looking at line 35 in the active.sh script:

sed -i "s/#COMPANY#/$company/" $HOME/data/$domain/index.htm

Here, the script attempts to replace #COMPANY# in the index.htm file with the value of $company. However, since $company has not been set anywhere in the script, this results in an "unbound variable" error.

**Comment by Gray-0men** [comment]
Same issue on a fresh install of kali, I get ARIN results for Name and Email and that's it
What did you do to fix?
ran update on 10/7/2024
