### ISSUE TITLE
Error's on Passive Serach __No such file or directory

### ISSUE THREAD

**Issue by Knitesh026** [leebaird/discover#211]
_____  ___  _____  _____  _____  _    _  _____  _____
|     \  |  |____  |      |     |  \  /  |____  |____/
|_____/ _|_ _____| |_____ |_____|   \/   |_____ |    \_

By Lee Baird

Uses ARIN, DNSRecon, dnstwist, goog-mail, goohost, theHarvester,
Metasploit, Whois, multiple websites, and recon-ng.

[*] Acquire API keys for maximum results with theHarvester.
[*] Add keys to /root/.theHarvester/api-keys.yaml

==================================================================

Usage

Company: Target
Domain:  target.com

==================================================================

Company: airvincible 
Domain:  airvincible.com

==================================================================

ARIN
    Email                (1/46)
    Names                (2/46)

![Screenshot_2024-10-28_00_56_49](https://github.com/user-attachments/assets/65121d06-5c32-49b1-874d-fb680f081808)

**Comment by leebaird** [comment]
Bugs fixed.
