### ISSUE TITLE
Can't use passive domain recon and xwatchwin problem

### ISSUE THREAD

**Issue by lgoqne** [leebaird/discover#212]
![VirtualBoxVM_dmLpDUt9Hy](https://github.com/user-attachments/assets/4875dadf-3600-49bf-95ee-ef47665cce5f)
Can't do passive recon on domain and

![VirtualBoxVM_MAa0OyZFzd](https://github.com/user-attachments/assets/abd34415-9a1f-4cf7-b9d0-59ab323d37fe)

everything else is working fine

**Comment by leebaird** [comment]
This was because there was an exist statement if ARIN was unable to pull down any data. This has been removed.
The xwatchwin is a package issue and should be reported to via Kali bug tracker.

**Comment by lgoqne** [comment]
Hey thanks for the support!
