### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by wermaxta** [leebaird/discover#34]
Hi i have problem with discover i got this error message 
Injection is not working. Reconnect your wireless card and try again.
and when i choice option 11. Crack WiFi is did not happen nothing.
My OS is Kali Linux 2 Sana 
Linux kali 4.0.0-kali1-686-pae #1 SMP Debian 4.0.4-1+kali2 (2015-06-03) i686 GNU/Linux

**Comment by leebaird** [comment]
Discover does a check to see if you have a wireless device connected, then it checks to see if the device able to inject packets. This test will often fail on my OS X. I disconnect my Alpha, wait about 10 sec, reconnect, then rerun Discover.
