### ISSUE TITLE
Person searching

### ISSUE THREAD

**Issue by ccali14** [leebaird/discover#39]
When I tested using non-english params, discover doesn't work properly.Like as my name

**Comment by bklnz** [comment]
Seems person searching just doesn't work in the latest version.  I just updated and running against a domain for which I got 85 names on Monday returned none.

**Comment by L1ghtn1ng** [comment]
What domain are you using?

**Comment by bklnz** [comment]
g4s.com

**Comment by jayw0k** [comment]
checking this domain today, yields 81 names. can you run again to confirm you results?

**Comment by ccali14** [comment]
Sure, I'll test and write down result in day
