### ISSUE TITLE
URLCrazy errors

### ISSUE THREAD

**Issue by leebaird** [leebaird/discover#40]
URLCrazy                  (20/26)
/usr/share/urlcrazy/tld.rb:81: warning: key "2nd_level_registration" is duplicated and overwritten on line 81
/usr/share/urlcrazy/tld.rb:89: warning: key "2nd_level_registration" is duplicated and overwritten on line 89
/usr/share/urlcrazy/tld.rb:91: warning: key "2nd_level_registration" is duplicated and overwritten on line 91

**Comment by L1ghtn1ng** [comment]
Deleting those lines in the code fix that. Also it seems urlcrazy is no longer maintained. I would suggest opening a kali bug for it so they can put a patch in to remove those lines.

**Comment by jayw0k** [comment]
If you wanted to remedy this within discover, the following could be added to update.sh
    tlddir=$(locate homophones.rb | sed 's%/[^/]*$%/%')
    cd $tlddir
    cp tld.rb tld.rb.bak
    cat tld.rb | grep '"bd"=>' -v | grep '"bn"=>' -v | grep '"br"=>' -v > tld_tmp.rb
    mv tld_tmp.rb tld.rb

**Comment by leebaird** [comment]
jayw0k, please add your fix.

**Comment by leebaird** [comment]
Nice job!
