### ISSUE TITLE
DNSdumpster

### ISSUE THREAD

**Issue by leebaird** [leebaird/discover#47]
https://dnsdumpster.com

Notice after you do a query, there is a button below to d/l results in csv.

**Comment by L1ghtn1ng** [comment]
What about DNS script that I sent you?

**Comment by leebaird** [comment]
Crap, still need to test that. sorry man.

On Thu, Mar 17, 2016 at 10:38 AM, J.Townsend <notifications@github.com>
wrote:

> What about DNS script that I sent you?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/leebaird/discover/issues/47#issuecomment-197907110>
>



-- 

Lee Baird
615-293-7625

**Comment by L1ghtn1ng** [comment]
That is alright cannot wait to get that script of mine in the repo

**Comment by leebaird** [comment]
Please coordinate with Jason.
He's working on it as well.

On Thu, Mar 17, 2016 at 11:12 AM, J.Townsend <notifications@github.com>
wrote:

> That is alright cannot wait to get that script of mine in the repo
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/leebaird/discover/issues/47#issuecomment-197926573>
>



-- 

Lee Baird
615-293-7625

**Comment by L1ghtn1ng** [comment]
Jason can you drop me a ping as I cannot find your email address

**Comment by leebaird** [comment]
Possibly add a new page called Map.

**Comment by leebaird** [comment]
complete
