### ISSUE TITLE
Strange output after urlvoid.com

### ISSUE THREAD

**Issue by leebaird** [leebaird/discover#49]
dnssy.com                 (25/29)
email-format.com          (26/29)
ewhois.com                (27/29)
myipneighbors.net         (28/29)
urlvoid.com               (29/29)
QFont::setPixelSize: Pixel size <= 0 (0)
QFont::setPixelSize: Pixel size <= 0 (0)

===============================================================================

***Scan complete.***

**Comment by L1ghtn1ng** [comment]
Did that start after you updated kali?

**Comment by leebaird** [comment]
Yes

**Comment by L1ghtn1ng** [comment]
Will have a look 
On 22 Mar 2016 5:54 p.m., Lee Baird <notifications@github.com> wrote:Yes

**Comment by jayw0k** [comment]
cutycapt is causing his for some reason - in both Kali & Ubuntu. I'll have a look as well when I am back in later.

**Comment by jayw0k** [comment]
cutycapt is causing this for some reason - in both Kali & Ubuntu.  Will have a look as well.

**Comment by L1ghtn1ng** [comment]
I have fixed this
