### ISSUE TITLE
pipl URL not returning results

### ISSUE THREAD

**Issue by leebaird** [leebaird/discover#52]
The URL is correct, but I think we maybe mission a cookie.

https://pipl.com/search/?q=$firstName+$lastName&l=&sloc=&in=5 &

**Comment by jayw0k** [comment]
Need to escape the ampersands:
$web https://pipl.com/search/?q=$firstName+$lastName\&l=\&sloc=\&in=5 &

**Comment by L1ghtn1ng** [comment]
Yeah I ran in to that issue when adding the hide result parameter for the ssllabs page

**Comment by leebaird** [comment]
Thanks jayw0k.
