### ISSUE TITLE
Create Directory for Passive Domain Reconnaissance.

### ISSUE THREAD

**Issue by DaKahuna** [leebaird/discover#60]
When running a passive reconnaissance against a domain, the target directory is not being created in /opt/discover/ resulting in write errors. 
[Pass_Recon.txt](https://github.com/leebaird/discover/files/257847/Pass_Recon.txt)

**Comment by L1ghtn1ng** [comment]
Hi, have you ran the update.sh? Also in the text file your output has missing tools, what OS are you running on?

**Comment by DaKahuna** [comment]
Yes, after following the install from github I ran the ./update.sh which completed successfully.

I am running this on a Kali-Linux 2.0 VM under Fusion.

**Comment by L1ghtn1ng** [comment]
There is your problem, you are on kali 2.0 which we and kali guys do not support. We only support kali rolling. You will want to download the new ISO and use that.

**Comment by DaKahuna** [comment]
I'll download and update - thanks.
