### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by tUn4** [leebaird/discover#61]
Hi,
when i try perform update function in menu "15. Update", i got an error "./discover.sh: line 3986: /update.sh: No such file or directory".
And i discovered that, in discover.sh file, the command in line 31 was not get correct path of file and $discover var is empty.
After i add command "updatedb" before line 31, it run correctly.
i use kali 2016.1 - Kali Rolling.

**Comment by L1ghtn1ng** [comment]
Okay thanks will fix that

**Comment by L1ghtn1ng** [comment]
pushed a fix, so give it a try on a clean install and let me know, thanks.
