### ISSUE TITLE
Parse SalesForce

### ISSUE THREAD

**Issue by flamecopper** [leebaird/discover#62]
Do I export the csv file and list it down here?

Create a free account at salesforce (https://connect.data.com/login).
Perform a search on your target company > select the company name > see all.
Copy the results into a new file.

Enter the location of your file:

What is the parser suppose to do?

**Comment by L1ghtn1ng** [comment]
It parses the output of the file with the rest of the output that discover finds

**Comment by flamecopper** [comment]
No, it doesn't work.

By Lee Baird


Create a free account at salesforce (https://connect.data.com/login).
Perform a search on your target company > select the company name > see all.
Copy the results into a new file.

Enter the location of your file:
~/Desktop/public/5132016-15_21_36-ConnectExport.csv

=====================================================================================

                           *** Invalid choice or entry. ***

=====================================================================================


Even though my file is right here.

root@osboxes:~/Desktop/public# ls
5132016-15_21_36-ConnectExport.csv  Metasploit  metasploitHelper


Alvin Oo,Tel:(65)91172830
New Email Address : oo.yekei.alvin@gmail.com
MPP ID: D1000749

**Comment by L1ghtn1ng** [comment]
Can you upload the file to github if it is possible. This will help debugging purposes

**Comment by flamecopper** [comment]
Hi Leebaird,

Please advise the correct steps.


Alvin Oo,Tel:(65)91172830
New Email Address : oo.yekei.alvin@gmail.com
MPP ID: D1000749

**Comment by leebaird** [comment]
Its not built to parse the csv. You need to copy the text from the screen and paste it into a new txt file. Then run the Discover against that.

**Comment by L1ghtn1ng** [comment]
From this I think it will be best to explicitly say paste the output in to a txt file

**Comment by leebaird** [comment]
Please go ahead and fix.

—

Lee

**Comment by L1ghtn1ng** [comment]
Okay will do

**Comment by L1ghtn1ng** [comment]
Will do it when I get back
