### ISSUE TITLE
Consider enhancing subdomain bruteforce by replacing Fierce with subbrute

### ISSUE THREAD

**Issue by iancnorden** [leebaird/discover#73]
Take a look at this, https://github.com/TheRook/subbrute. Significant wordlists compared to Fierce, but they do rely on open resolvers for efficiency and to reduce chance of blocking the brute forcing.

**Comment by leebaird** [comment]
I have done some testing of this tool using the namelist from dnsrecon. There are a lot of false positives and the tool always seems to hang. I have email the author or dnsrecon to see if certain features could be added to his tool.
