### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Jzakhary00** [leebaird/discover#74]
Hi, after running a passive domain scan, i receive the following error: 

cat: names-tmp: No such file or directory
./discover.sh: line 636: /root/data/https://www.sweetstreet.com/store/buy-cupcakes-online.html/data/hosts.htm: No such file or directory
./discover.sh: line 636: /root/data/https://www.sweetstreet.com/store/buy-cupcakes-online.html/data/hosts.htm: No such file or directory
./discover.sh: line 652: /root/data/https://www.sweetstreet.com/store/buy-cupcakes-online.html/data/emails.htm: No such file or directory
./discover.sh: line 662: /root/data/https://www.sweetstreet.com/store/buy-cupcakes-online.html/data/names.htm: No such file or directory
./discover.sh: line 700: /root/data/https://www.sweetstreet.com/store/buy-cupcakes-online.html/data/subdomains.htm: No such file or directory
./discover.sh: line 759: /root/data/https://www.sweetstreet.com/store/buy-cupcakes-online.html/data/whois-domain.htm: No such file or directory
./discover.sh: line 759: /root/data/https://www.sweetstreet.com/store/buy-cupcakes-online.html/data/whois-domain.htm: No such file or directory
./discover.sh: line 766: /root/data/https://www.sweetstreet.com/store/buy-cupcakes-online.html/data/whois-ip.htm: No such file or directory
./discover.sh: line 766: /root/data/https://www.sweetstreet.com/store/buy-cupcakes-online.html/data/whois-ip.htm: No such file or directory
./discover.sh: line 769: /root/data/https://www.sweetstreet.com/store/buy-cupcakes-online.html/data/names.htm: No such file or directory
./discover.sh: line 770: /root/data/https://www.sweetstreet.com/store/buy-cupcakes-online.html/data/squatting.htm: No such file or directory
./discover.sh: line 771: /root/data/https://www.sweetstreet.com/store/buy-cupcakes-online.html/data/subdomains.htm: No such file or directory
./discover.sh: line 773: /root/data/https://www.sweetstreet.com/store/buy-cupcakes-online.html/data/passive-recon.htm: No such file or directory
./discover.sh: line 773: /root/data/https://www.sweetstreet.com/store/buy-cupcakes-online.html/data/passive-recon.htm: No such file or directory
/root/data/https://www.sweetstreet.com/store/buy-cupcakes-online.html/images/robtex.png: No such file or directory

**Comment by L1ghtn1ng** [comment]
Hi did you run update.sh first, also did you clone in to /opt ?

**Comment by L1ghtn1ng** [comment]
Also from looking at the output you put the URL as the folder name of the scan instead of just sweetstreat

**Comment by Jzakhary00** [comment]
Hi, I did both.

**Comment by Jzakhary00** [comment]
Hey, how would I change that?

**Comment by L1ghtn1ng** [comment]
When you do a passive scan the first option when it says hostname put the name sweet street no spaces, then next option is the url

**Comment by leebaird** [comment]
I just performed a passive test using the following with no errors.
Company: Sweet Street
Domain: sweetstreet.com
