### ISSUE TITLE
Import Error for theHarvester

### ISSUE THREAD

**Issue by Slad3G** [leebaird/discover#87]
Hey Lee,

Great tool, I've loved the functionality and recently updated to the latest version. After the update I get a few errors that appear to be an order of operations thing. 

error:
`Traceback (most recent call last):
  File "/usr/bin/theHarvester", line 17, in <module>
    from discovery import *`

I'm working  through some other things and will post them here if I can't figure them out. Thanks again for such a great tool.

SG

**Comment by L1ghtn1ng** [comment]
Thanks for the bug report. Any extra information you can provide will be great. I will see what I can find and push a fix.

**Comment by L1ghtn1ng** [comment]
I have identified the issue. I am going to revert a change that we did recently until we work this one out properly, please follow #88 for updates. CC @leebaird
