### ISSUE TITLE
theHarverster issues

### ISSUE THREAD

**Issue by L1ghtn1ng** [leebaird/discover#88]
This is to consolidate all theHarverster issues that have been identified and one place to track them

- #87 
-
 ```
./discover.sh: line 312: /usr/bin/theHarvester: Permission denied
     Bing                 (10/33)
./discover.sh: line 314: /usr/bin/theHarvester: Permission denied
     Dogpilesearch        (11/33)
./discover.sh: line 316: /usr/bin/theHarvester: Permission denied
     Google               (12/33)
./discover.sh: line 318: /usr/bin/theHarvester: Permission denied
     Google CSE           (13/33)
./discover.sh: line 320: /usr/bin/theHarvester: Permission denied
     Google+              (14/33)
./discover.sh: line 322: /usr/bin/theHarvester: Permission denied
     Google Profiles	  (15/33)
./discover.sh: line 324: /usr/bin/theHarvester: Permission denied
     Jigsaw               (16/33)
./discover.sh: line 326: /usr/bin/theHarvester: Permission denied
     LinkedIn             (17/33)
./discover.sh: line 328: /usr/bin/theHarvester: Permission denied
     PGP                  (18/33)
./discover.sh: line 330: /usr/bin/theHarvester: Permission denied
     Yahoo                (19/33)
./discover.sh: line 332: /usr/bin/theHarvester: Permission denied
     All                  (20/33)
./discover.sh: line 334: /usr/bin/theHarvester: Permission denied
```
Is due to not having 700 file permissions. This was identified on a test VM with a clean install of kali

Kali are patching the file with this which is why we are running in to issue 87
```
 --- a/theHarvester.py
 +++ b/theHarvester.py
   @@ -7,6 +7,7 @@ import os
   from socket import *
   import re
   import getopt
  +sys.path.append("/usr/share/theharvester/")
  
 try:
    import requests
```

**Comment by leebaird** [comment]
Removed from update.sh.

**Comment by brohan** [comment]
1st, came across Lee's Hack3rcon vids which led me hear. Thank you very much. I installed your script on a fresh install of Kali 2017.1 and got similar errors. I merely cloned the git and ran ./update.  Here are the errors:

goog-mail                 (6/34)
./discover.sh: line 297: /lib/live/mount/persistence/sdc3/rw/root/discover: Is a directory

goohost
     IP                   (7/34)
./discover.sh: line 302: /lib/live/mount/persistence/sdc3/rw/root/discover: Is a directory
     Email                (8/34)
./discover.sh: line 304: /lib/live/mount/persistence/sdc3/rw/root/discover: Is a directory
cat: 'report-*': No such file or directory
rm: cannot remove '*-infosecposse.com.txt': No such file or directory

theHarvester
     Baidu                (9/34)
./discover.sh: line 321: /usr/share/theharvester/theHarvester.py: Permission denied
     Bing                 (10/34)
./discover.sh: line 323: /usr/share/theharvester/theHarvester.py: Permission denied
     Dogpilesearch        (11/34)
./discover.sh: line 325: /usr/share/theharvester/theHarvester.py: Permission denied
     Google               (12/34)
./discover.sh: line 327: /usr/share/theharvester/theHarvester.py: Permission denied
     Google CSE           (13/34)
./discover.sh: line 329: /usr/share/theharvester/theHarvester.py: Permission denied
     Google+              (14/34)
./discover.sh: line 331: /usr/share/theharvester/theHarvester.py: Permission denied
     Google Profiles      (15/34)
./discover.sh: line 333: /usr/share/theharvester/theHarvester.py: Permission denied
     Jigsaw               (16/34)
./discover.sh: line 335: /usr/share/theharvester/theHarvester.py: Permission denied
     LinkedIn             (17/34)
./discover.sh: line 337: /usr/share/theharvester/theHarvester.py: Permission denied
     PGP                  (18/34)
./discover.sh: line 339: /usr/share/theharvester/theHarvester.py: Permission denied
     Yahoo                (19/34)
./discover.sh: line 341: /usr/share/theharvester/theHarvester.py: Permission denied
     All                  (20/34)
./discover.sh: line 343: /usr/share/theharvester/theHarvester.py: Permission denied

Metasploit                (21/34)

URLCrazy                  (22/34)

Whois
     Domain               (23/34)
     IP                   (24/34)

dnsdumpster.com           (25/34)
/root/data/infosecposse.com/images/dnsdumpster.png: No such file or directory
dnswatch.info             (26/34)
./discover.sh: line 515: /root/data/infosecposse.com/data/records.htm: No such file or directory
./discover.sh: line 516: /root/data/infosecposse.com/data/records.htm: No such file or directory
./discover.sh: line 517: /root/data/infosecposse.com/data/records.htm: No such file or directory
./discover.sh: line 518: /root/data/infosecposse.com/data/records.htm: No such file or directory
./discover.sh: line 519: /root/data/infosecposse.com/data/records.htm: No such file or directory
email-format.com          (27/34)
ewhois.com                (28/34)
intodns.com               (29/34)
./discover.sh: line 531: /root/data/infosecposse.com/pages/config.htm: No such file or directory
myipneighbors.net         (30/34)
netcraft.com              (31/34)
./discover.sh: line 549: /root/data/infosecposse.com/pages/netcraft.htm: No such file or directory
./discover.sh: line 550: /root/data/infosecposse.com/pages/netcraft.htm: No such file or directory
./discover.sh: line 551: /root/data/infosecposse.com/pages/netcraft.htm: No such file or directory
./discover.sh: line 552: /root/data/infosecposse.com/pages/netcraft.htm: No such file or directory
./discover.sh: line 553: /root/data/infosecposse.com/pages/netcraft.htm: No such file or directory
ultratools.com            (32/34)
./discover.sh: line 580: /root/data/infosecposse.com/data/zonetransfer.htm: No such file or directory
./discover.sh: line 583: /root/data/infosecposse.com/data/zonetransfer.htm: No such file or directory
./discover.sh: line 584: /root/data/infosecposse.com/data/zonetransfer.htm: No such file or directory
./discover.sh: line 585: /root/data/infosecposse.com/data/zonetransfer.htm: No such file or directory
Domains                   (33/34)
./discover.sh: line 623: break: only meaningful in a `for', `while', or `until' loop
./discover.sh: line 647: /root/data/infosecposse.com/data/domains.htm: No such file or directory
./discover.sh: line 648: /root/data/infosecposse.com/data/domains.htm: No such file or directory

sed: can't read names1: No such file or directory
recon-ng                  (34/34)

cat: /lib/live/mount/persistence/sdc3/rw/root/discover: Is a directory
usage: recon-ng [-h] [-v] [-w workspace] [-r filename] [--no-check]
                [--no-analytics]
recon-ng: error: unrecognized arguments: /root/discover/tmp.rc
grep: /tmp/emails: No such file or directory
grep: /tmp/names: No such file or directory
grep: /tmp/networks: No such file or directory
grep: /tmp/subdomains: No such file or directory
cat: networks-tmp: No such file or directory
./discover.sh: line 749: /root/data/infosecposse.com/data/hosts.htm: No such file or directory
./discover.sh: line 749: /root/data/infosecposse.com/data/hosts.htm: No such file or directory
./discover.sh: line 768: /root/data/infosecposse.com/data/emails.htm: No such file or directory
./discover.sh: line 768: /root/data/infosecposse.com/data/emails.htm: No such file or directory
./discover.sh: line 778: /root/data/infosecposse.com/data/names.htm: No such file or directory
./discover.sh: line 778: /root/data/infosecposse.com/data/names.htm: No such file or directory
./discover.sh: line 817: /root/data/infosecposse.com/data/domains.htm: No such file or directory
./discover.sh: line 817: /root/data/infosecposse.com/data/domains.htm: No such file or directory
./discover.sh: line 827: /root/data/infosecposse.com/data/subdomains.htm: No such file or directory
./discover.sh: line 827: /root/data/infosecposse.com/data/subdomains.htm: No such file or directory
./discover.sh: line 886: /root/data/infosecposse.com/data/whois-domain.htm: No such file or directory
./discover.sh: line 886: /root/data/infosecposse.com/data/whois-domain.htm: No such file or directory
./discover.sh: line 894: /root/data/infosecposse.com/data/whois-ip.htm: No such file or directory
./discover.sh: line 894: /root/data/infosecposse.com/data/whois-ip.htm: No such file or directory
./discover.sh: line 897: /root/data/infosecposse.com/data/passive-recon.htm: No such file or directory
./discover.sh: line 897: /root/data/infosecposse.com/data/passive-recon.htm: No such file or directory
/root/data/infosecposse.com/images/robtex.png: No such file or directory

**Comment by brohan** [comment]
1st, came across Lee's Hack3rcon vids which led me hear. Thank you very much. I installed your script on a fresh install of Kali 2017.1 and got similar errors. I merely cloned the git and ran ./update. Here are the errors (I am running Kali on a LiveUSB):

Usage

Company: Target
Domain:  target.com

==================================================================

Company: dove property
Domain:  dovepropertymanagement.com
cp: target '/root/data/dovepropertymanagement.com' is not a directory
sed: can't read /root/data/dovepropertymanagement.com/index.htm: No such file or directory
mv: cannot move 'tmp' to '/root/data/dovepropertymanagement.com/index.htm': No such file or directory

==================================================================

ARIN
     Email                (1/34)
     Names                (2/34)
     Networks             (3/34)

dnsrecon                  (4/34)

goofile                   (5/34)

goog-mail                 (6/34)
./discover.sh: line 297: /lib/live/mount/persistence/sdc3/rw/root/discover: Is a directory

goohost
     IP                   (7/34)
./discover.sh: line 302: /lib/live/mount/persistence/sdc3/rw/root/discover: Is a directory
     Email                (8/34)
./discover.sh: line 304: /lib/live/mount/persistence/sdc3/rw/root/discover: Is a directory
cat: 'report-*': No such file or directory
rm: cannot remove '*-dovepropertymanagement.com.txt': No such file or directory

theHarvester
     Baidu                (9/34)
./discover.sh: line 321: /usr/share/theharvester/theHarvester.py: Permission denied
     Bing                 (10/34)
./discover.sh: line 323: /usr/share/theharvester/theHarvester.py: Permission denied
     Dogpilesearch        (11/34)
./discover.sh: line 325: /usr/share/theharvester/theHarvester.py: Permission denied
     Google               (12/34)
./discover.sh: line 327: /usr/share/theharvester/theHarvester.py: Permission denied
     Google CSE           (13/34)
./discover.sh: line 329: /usr/share/theharvester/theHarvester.py: Permission denied
     Google+              (14/34)
./discover.sh: line 331: /usr/share/theharvester/theHarvester.py: Permission denied
     Google Profiles      (15/34)
./discover.sh: line 333: /usr/share/theharvester/theHarvester.py: Permission denied
     Jigsaw               (16/34)
./discover.sh: line 335: /usr/share/theharvester/theHarvester.py: Permission denied
     LinkedIn             (17/34)
./discover.sh: line 337: /usr/share/theharvester/theHarvester.py: Permission denied
     PGP                  (18/34)
./discover.sh: line 339: /usr/share/theharvester/theHarvester.py: Permission denied
     Yahoo                (19/34)
./discover.sh: line 341: /usr/share/theharvester/theHarvester.py: Permission denied
     All                  (20/34)
./discover.sh: line 343: /usr/share/theharvester/theHarvester.py: Permission denied

**Comment by L1ghtn1ng** [comment]
You need to make sure you have discover in /opt/ I do however not sure if it will run correctly as to my knowledge a live usb has not been tested on

Sent from phone

________________________________

**Comment by brohan** [comment]
I placed the discover directory into the opt dir here is the outcome:

Company: dove
Domain:  www.dovepropertymanagement.com
cp: cannot stat '/report/': No such file or directory
sed: can't read /root/data/www.dovepropertymanagement.com/index.htm: No such file or directory
mv: cannot move 'tmp' to '/root/data/www.dovepropertymanagement.com/index.htm': No such file or directory

==================================================================

ARIN
     Email                (1/34)
     Names                (2/34)
     Networks             (3/34)
           DOVE

dnsrecon                  (4/34)

goofile                   (5/34)

goog-mail                 (6/34)
/opt/discover/./discover.sh: line 297: /mods/goog-mail.py: No such file or directory

goohost
     IP                   (7/34)
/opt/discover/./discover.sh: line 302: /mods/goohost.sh: No such file or directory
     Email                (8/34)
/opt/discover/./discover.sh: line 304: /mods/goohost.sh: No such file or directory
cat: 'report-*': No such file or directory
rm: cannot remove '*-www.dovepropertymanagement.com.txt': No such file or directory

theHarvester
     Baidu                (9/34)
/opt/discover/./discover.sh: line 321: /usr/share/theharvester/theHarvester.py: Permission denied
     Bing                 (10/34)
/opt/discover/./discover.sh: line 323: /usr/share/theharvester/theHarvester.py: Permission denied
     Dogpilesearch        (11/34)
/opt/discover/./discover.sh: line 325: /usr/share/theharvester/theHarvester.py: Permission denied
     Google               (12/34)
/opt/discover/./discover.sh: line 327: /usr/share/theharvester/theHarvester.py: Permission denied
     Google CSE           (13/34)
/opt/discover/./discover.sh: line 329: /usr/share/theharvester/theHarvester.py: Permission denied
     Google+              (14/34)
/opt/discover/./discover.sh: line 331: /usr/share/theharvester/theHarvester.py: Permission denied
     Google Profiles      (15/34)
/opt/discover/./discover.sh: line 333: /usr/share/theharvester/theHarvester.py: Permission denied
     Jigsaw               (16/34)
/opt/discover/./discover.sh: line 335: /usr/share/theharvester/theHarvester.py: Permission denied
     LinkedIn             (17/34)
/opt/discover/./discover.sh: line 337: /usr/share/theharvester/theHarvester.py: Permission denied
     PGP                  (18/34)
/opt/discover/./discover.sh: line 339: /usr/share/theharvester/theHarvester.py: Permission denied
     Yahoo                (19/34)
/opt/discover/./discover.sh: line 341: /usr/share/theharvester/theHarvester.py: Permission denied
     All                  (20/34)
/opt/discover/./discover.sh: line 343: /usr/share/theharvester/theHarvester.py: Permission denied

**Comment by L1ghtn1ng** [comment]
To fix the harvester issue you need to chmod 700 the file also try running the update file again

Sent from phone

________________________________

**Comment by brohan** [comment]
Update:
FWIW when I ran the update script (this is being run on a liveUSB locating homophones manuall gives me 2 results):

./update.sh: line 11: cd: too many arguments
cp: cannot stat 'tld.rb': No such file or directory
cat: tld.rb: No such file or directory
Updating Kali.

When running discover, domain, passive much better results after making harvester executable:

==================================================================

Usage

Company: Target
Domain:  target.com

==================================================================

Company: dove
Domain:  www.dovepropertymanagement.com
cp: target '/root/data/www.dovepropertymanagement.com' is not a directory
sed: can't read /root/data/www.dovepropertymanagement.com/index.htm: No such file or directory
mv: cannot move 'tmp' to '/root/data/www.dovepropertymanagement.com/index.htm': No such file or directory

==================================================================

ARIN
     Email                (1/34)
     Names                (2/34)
     Networks             (3/34)
           DOVE

dnsrecon                  (4/34)

goofile                   (5/34)

goog-mail                 (6/34)
./discover.sh: line 297: /lib/live/mount/persistence/sdc3/rw/opt/discover: Is a directory

goohost
     IP                   (7/34)
./discover.sh: line 302: /lib/live/mount/persistence/sdc3/rw/opt/discover: Is a directory
     Email                (8/34)
./discover.sh: line 304: /lib/live/mount/persistence/sdc3/rw/opt/discover: Is a directory
cat: 'report-*': No such file or directory
rm: cannot remove '*-www.dovepropertymanagement.com.txt': No such file or directory

theHarvester
     Baidu                (9/34)
     Bing                 (10/34)
     Dogpilesearch        (11/34)
     Google               (12/34)
     Google CSE           (13/34)
     Google+              (14/34)
     Google Profiles      (15/34)
     Jigsaw               (16/34)
     LinkedIn             (17/34)
     PGP                  (18/34)
     Yahoo                (19/34)
     All                  (20/34)

Metasploit                (21/34)
^CTerminating...

**Comment by brohan** [comment]
I am now having another issue later on down that script which I will post below, not harvester related (I don't think). When I get done, and go to /root/data, there are NO files present.

http://paste.ubuntu.com/24567862/

**Comment by L1ghtn1ng** [comment]
The rest of your issues stem from it being a live usb, the team will have to do some testing to fix this. Thanks for the bug report.

Sent from phone

________________________________

**Comment by brohan** [comment]
Thank you for the prompt help, I really appreciate it.
