### ISSUE TITLE
Automated version \ script?

### ISSUE THREAD

**Issue by Dviros** [leebaird/discover#91]
Hi!
I would like to have an automated version of the discover tool - active and passive recon, nikto on the hosts with screenshots, inside the complete report generated.
Is it possible?
Thanks a lot!
Dvir

**Comment by L1ghtn1ng** [comment]
So I understand this correctly you want it to do active and passive scanning with nikto by having a switch for example?

From: Dviros
Sent: Sunday, 1 January, 17:27
Subject: [leebaird/discover] Automated version \ script? (#91)
To: leebaird/discover
Cc: Subscribed

Hi!
I would like to have an automated version of the discover tool - active and passive recon, nikto on the hosts with screenshots, inside the complete report generated.
Is it possible?
Thanks a lot!
Dvir

**Comment by leebaird** [comment]
Nikto is used for enumerating website and not considered a recon tool.
