### ISSUE TITLE
Which version of pyinstaller do you use?

### ISSUE THREAD

**Issue by tsluyter** [leebaird/discover#95]
Most recent versions of pyinstaller do not cross-compile towards the Windows platform anymore. Thus the instructions in this list won't work anymore and will result in a Linux executable.

**Comment by L1ghtn1ng** [comment]
We do not use pyinstaller, can you please expand on what you are doing and screenshots please?

Sent from phone

________________________________

**Comment by tsluyter** [comment]
Sorry, my bad... This was regarding your notes/pwk.txt file :) 

https://github.com/leebaird/discover/blob/master/notes/pwk.txt

**Comment by leebaird** [comment]
Sorry, but I do not remember. That's been at least 2 years ago.
