### ISSUE TITLE
Switch from ssconvert to xlsx2csv

### ISSUE THREAD

**Issue by l0stkn0wledge** [leebaird/discover#97]
Gnumeric is extremely dependency dependent, so it is is bloated to install on small/headless systems, for a simple conversion tool (ssconvert). The xlsx2csv is smaller with fewer dependencies and should hopefully accomplish the same task.

**Comment by leebaird** [comment]
Thanks for the heads up, we will take a look.

**Comment by L1ghtn1ng** [comment]
I have implemented this, just update and should be good :-)
