### ISSUE TITLE
/usr/share/theharvester/theHarvester.py not executable on Kali by default?

### ISSUE THREAD

**Issue by sypherspace** [leebaird/discover#99]
From a fresh Kali install using the 2017.01 media, cloning the repo into /opt/discover per the instructions, a number of checks fail because `/usr/share/theharvester/theHarvester.py` is not executable by default.

I fixed this by adding the execute bit to `/usr/share/theharvester/theHarvester.py`. There might be a better option.

**Comment by L1ghtn1ng** [comment]
There is a ticket upstream on the Kali bug tracker but they have not done anything about it yet as far as I am aware

Sent from phone

________________________________

**Comment by sypherspace** [comment]
Would it be worth calling the python binary with the script as a parameter rather than assuming that the script itself is +x? I can put together a PR for that.

**Comment by L1ghtn1ng** [comment]
Go for it and I will take a look

Sent from phone

________________________________

**Comment by sypherspace** [comment]
Opened PR #100 .

**Comment by leebaird** [comment]
chmod 755 theHarvester.py
